### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by GreyElaina** [hsfzxjy/lambdex#1]
I hope to provide features such as `async def`, `await`, `async for`, `async with` etc.

**Comment by hsfzxjy** [comment]
Thanks for feedback! It's on the plan, and will be ready in the upcoming versions.

**Comment by hsfzxjy** [comment]
Keywords `async_def_`, `async_for_`, `async_with_` and `await_` are now supported. See https://github.com/hsfzxjy/lambdex#async-and-await for more details.
